#端口号
server:
  port: 9000

#数据源
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/quick_app?serverTimezone=UTC
    username: root
    password: App-:1234
    driver-class-name: com.mysql.cj.jdbc.Driver

